=== Thomas-Elder/cosc2467.assignment-one/Patient.dtd
<!-- Patients -->
<!ELEMENT Patients (Patient*)>

  <!-- Patient -->
    <!ELEMENT Patient ( Allergy*,
    					AdverseDrugReaction*,
    					ChronicCondition*,
    					LanguageSpoken+,
    					Visit*,
    					Admission* )>

    	<!ATTLIST Patient name CDATA #REQUIRED>
        <!ATTLIST Patient gender (male | female | neither) #REQUIRED>
        <!ATTLIST Patient dateOfBirth CDATA #REQUIRED>
        <!ATTLIST Patient bloodType (Oneg|Opos|Aneg|Apos|Bneg|Bpos|ABneg|ABpos) #REQUIRED> <!--restrict to legit blood types -->

    	<!ELEMENT Allergy EMPTY>
    	    <!ATTLIST Allergy allergen CDATA #REQUIRED>
    	
    	<!ELEMENT AdverseDrugReaction EMPTY>
    	    <!ATTLIST AdverseDrugReaction drug CDATA #REQUIRED>

    	<!ELEMENT ChronicCondition (#PCDATA)>
    	<!ELEMENT LanguageSpoken (#PCDATA)>

    	<!-- Visit -->
    	<!ELEMENT Visit ( Practitioner,
    					  Symptom+,
    					  Diagnosis,
    					  Prescription* )>

    		<!ATTLIST Visit dateOfVisit CDATA #REQUIRED>

    		<!-- Practitioner -->
    		<!ELEMENT Practitioner EMPTY>
			<!ATTLIST Practitioner name CDATA #REQUIRED>
    			<!ATTLIST Practitioner type CDATA #REQUIRED>
    		<!-- /Practitioner -->

    		<!ELEMENT Symptom (#PCDATA)>
    		<!ELEMENT Diagnosis (#PCDATA)>
    		<!ELEMENT Prescription (#PCDATA)>
    	<!-- /Visit -->


    	<!-- Admission -->
    	<!ELEMENT Admission ( ReasonForAdmission,
    						  Procedure* )>

    		<!ATTLIST Admission dateOfAdmission CDATA #REQUIRED>
    		<!ATTLIST Admission dateOfDischarge CDATA #REQUIRED>

    		<!ELEMENT ReasonForAdmission (#PCDATA)>
    		<!ELEMENT Procedure (#PCDATA)>

    	<!-- /Admission -->
    <!-- /Patient -->
<!-- Patients -->

=== Thomas-Elder/cosc2467.assignment-one/Patient.xml
<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE Patients SYSTEM "Patient.dtd">

<Patients>

    <!-- 1-4 -->
    <Patient name="Tom" gender="male" dateOfBirth="24/03/1986" bloodType="ABpos">

	    <!-- 8 -->
	    <LanguageSpoken>English</LanguageSpoken>

	    <!-- 9 b -->
	    <Visit dateOfVisit="10/09/2015">

        <!-- 9a -->
        <Practitioner name="Jen Little" type="General Practitioner" />

         <!-- 9c-->
        <Symptom>Lethargy</Symptom>
        <Symptom>Vomiting</Symptom>
        <Symptom>Nausea</Symptom>

        <!-- 9d -->
	    	<Diagnosis>Gastroenteritis</Diagnosis>

	   		 <!-- 9e -->
	    	<Prescription>Maxalon</Prescription>
	    </Visit>
   </Patient>

   <!-- 1-4 -->
   <Patient name="Suzy" gender="female" dateOfBirth="20/06/1978" bloodType="Opos"> 

        <!-- 5 -->
        <Allergy allergen="Peanuts" />
        <Allergy allergen="Barley" />

        <!-- 6 -->
        <AdverseDrugReaction drug="Penicillin" />
        <AdverseDrugReaction drug="Psuedoephidrin" />

        <!-- 7 -->
	    <ChronicCondition>Chronic Depression</ChronicCondition>

	    <!-- 8 -->
	    <LanguageSpoken>English</LanguageSpoken>
	    <LanguageSpoken>Bahasa Indonesia</LanguageSpoken>

	    <!-- 9 b -->
	    <Visit dateOfVisit="10/05/2015"> 

        <!-- 9a -->
        <Practitioner name="Doctor Freud" type="Psychologist" />

        <!-- 9c-->
        <Symptom>Lethargy</Symptom>
        <Symptom>Depression</Symptom>
        <Symptom>Thoughts of self-harm</Symptom>

        <!-- 9d -->
	    	<Diagnosis>Chronic Depression</Diagnosis>

	    	<!-- 9e -->
	    	<Prescription>Prozac</Prescription> 
	    </Visit>

	    <!-- 10a -->
	    <Admission dateOfAdmission="10/10/2015" dateOfDischarge="12/10/2015">

	        <!-- 10b -->
	        <ReasonForAdmission>Appendicitis</ReasonForAdmission>

	        <!-- 10c -->
	        <Procedure>Operation to remove appendix</Procedure>
	    </Admission>
   </Patient>
</Patients>
